# Generated by Django 3.2.4 on 2021-06-24 01:35

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome ')),
                ('genero', models.CharField(max_length=30, verbose_name='Gênero ')),
                ('etnia', models.CharField(max_length=200, verbose_name='Etnia ')),
                ('deficiencia', models.CharField(max_length=200, verbose_name='Deficiência ')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado ')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade ')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso ')),
                ('periodo', models.CharField(max_length=200, verbose_name='Periodo')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Email ')),
                ('linkedIn', models.CharField(blank=True, max_length=200, verbose_name='LinkedIn')),
                ('site', models.CharField(blank=True, max_length=200, verbose_name='Site pessoal ')),
                ('pessoal', models.CharField(blank=True, max_length=50, verbose_name='Telefone Pessoal ')),
                ('residencial', models.CharField(blank=True, max_length=50, verbose_name='Telefone Residencial ')),
                ('outro_tel', models.CharField(blank=True, max_length=50, verbose_name='Algum outro')),
                ('exp', models.TextField(blank=True, verbose_name='Experiência Profissional ')),
                ('atv', models.TextField(blank=True, verbose_name='Atividades Filantrópicas ')),
                ('var1', models.CharField(blank=True, max_length=50, verbose_name='Habilidade 1 ')),
                ('porc1', models.IntegerField(blank=True, default=1, verbose_name='Porcentagem 1')),
                ('var2', models.CharField(blank=True, max_length=50, verbose_name='Habilidade 2 ')),
                ('porc2', models.IntegerField(blank=True, verbose_name='Porcentagem 2')),
                ('var3', models.CharField(blank=True, max_length=50, verbose_name='Habilidade 3 ')),
                ('porc3', models.IntegerField(blank=True, verbose_name='Porcentagem 3')),
                ('var4', models.CharField(blank=True, max_length=50, verbose_name='Habilidade 4 ')),
                ('porc4', models.IntegerField(blank=True, verbose_name='Porcentagem 4')),
                ('idi1', models.CharField(blank=True, max_length=50, verbose_name='Idioma 1 ')),
                ('porc5', models.IntegerField(blank=True, verbose_name='Porcentagem 1')),
                ('idi2', models.CharField(blank=True, max_length=50, verbose_name='Idioma 2 ')),
                ('porc6', models.IntegerField(blank=True, verbose_name='Porcentagem 2')),
                ('idi3', models.CharField(blank=True, max_length=50, verbose_name='Idioma 3 ')),
                ('porc7', models.IntegerField(blank=True, verbose_name='Porcentagem 3')),
                ('idi4', models.CharField(blank=True, max_length=50, verbose_name='Idioma 4 ')),
                ('porc8', models.IntegerField(blank=True, verbose_name='Porcentagem 4')),
                ('enfu', models.CharField(blank=True, max_length=50, verbose_name='Ensino fundamental ')),
                ('enme', models.CharField(blank=True, max_length=50, verbose_name='Ensino médio ')),
                ('bach', models.CharField(blank=True, max_length=50, verbose_name='Bacharelado ')),
                ('mes', models.CharField(blank=True, max_length=50, verbose_name='Mestrado  ')),
                ('dout', models.CharField(blank=True, max_length=50, verbose_name='Doutorado  ')),
                ('arint', models.TextField(blank=True, verbose_name='Áreas de interesse ')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('objpe', models.TextField(blank=True, verbose_name='Objetivos Pessoais ')),
                ('objpro', models.TextField(blank=True, verbose_name='Objetivos Profissionais ')),
                ('imagem_banner', stdimage.models.StdImageField(upload_to='usuario', verbose_name='Imagem Banner')),
                ('imagem_perfil', stdimage.models.StdImageField(upload_to='usuario', verbose_name='Imagem Perfil')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('nome',),
            },
        ),
    ]
